export const Products=[
    {
        id:1,
        title:"Pen",
        price:200,
        img:"https://m.media-amazon.com/images/I/51H2NJN9B-L._SX466_.jpg"
    },
    {
        id:2,
        title:"Pencil",
        price:5,
        img:"https://4.imimg.com/data4/PL/IY/MY-23695144/natraj-pencil-500x500.jpg"
    },
    {
        id:3,
        title:"Eraser",
        price:10,
        img:"https://5.imimg.com/data5/KL/TH/MY-30911641/rubber-eraser-500x500.jpg"
    },
    {
        id:4,
        title:"Sharpner",
        price:10,
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTruDoJWPnVytRl73sqPjVcBGMuRndUl_yK8g&usqp=CAU"
    },
    {
        id:5,
        title:"Scale",
        price:20,
        img:"https://quickrly.com/wp-content/uploads/2020/08/SCALE.jpg"
    },
    {
        id:6,
        title:"Book",
        price:60,
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqvlUrtUxV4jS6bqve90lVWOZWISzDfRGS8Q&usqp=CAU"
    },
    {
        id:7,
        title:"Compass",
        price:100,
        img:"https://2.imimg.com/data2/UU/WR/MY-3431580/compass-box-500x500.jpg"
    },
    {
        id:8,
        title:"Geometry Kit",
        price:400,
        img:"https://sc04.alicdn.com/kf/HTB1EFVyXZvrK1Rjy0Feq6ATmVXag.jpg"
    },
    {
        id:9,
        title:"Pouch",
        price:100,
        img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFiRcnl14OX2DSmWBOlUUjS-SHgFUshnqfAQ&usqp=CAU"
    },
    {
        id:10,
        title:"Wightner",
        price:20,
        img:"https://5.imimg.com/data5/NN/PE/BX/SELLER-8586032/camlin-whitener-pen-500x500.jpg"
    },
    {
        id:11,
        title:"Key-Chain",
        price:50,
        img:"https://m.media-amazon.com/images/I/41MUrZOaU-L.jpg"
    },
    {
        id:12,
        title:"Stapler",
        price:80,
        img:"https://5.imimg.com/data5/SELLER/Default/2021/3/OT/KE/NY/24082910/stapler-no-10-stapler-with-c1113n-100-staples-500x500.jpeg"
    },
    {
        id:13,
        title:"Pad",
        price:120,
        img:"https://5.imimg.com/data5/NG/RD/MY-3274594/writing-pad-500x500.jpg"
    },
    {
        id:14,
        title:"Rounder",
        price:60,
        img:"https://m.media-amazon.com/images/I/61Nd1PuS-+L._SL1500_.jpg"
    }
]